import db from "./index";
import {readFileSync, writeFileSync} from "fs";
import {join} from "path";
import {sql} from "drizzle-orm";


function extractDOBlocks(sqlContent: string): string[] {
    const blockRegex = /DO \$\$[\s\S]*?END \$\$;\s*/g;
    const blocks: string[] = [];
    let match;

    console.log("SQL content to extract from:", sqlContent); // Log raw content

    while ((match = blockRegex.exec(sqlContent)) !== null) {
        console.log("Matched block:", match[0]); // Log each matched block
        blocks.push(match[0]);
    }

    console.log("Total extracted blocks:", blocks.length); // Log total blocks
    return blocks;
}

/**
 * Execute approved projects from the SQL file
 * This script reads 005_approved_projects.sql and executes it
 * Then clears the file after successful execution
 * Note: Projects are already deleted from pending_projects when approved
 */
async function approveProjects() {
    const sqlFilePath = join(__dirname, 'migrations', '005_approved_projects.sql');

    try {
        console.log('📂 Reading approved projects SQL file...');
        const sqlContent = readFileSync(sqlFilePath, "utf-8");

        if (!sqlContent.trim()) {
            console.log('ℹ️  No approved projects to process');
            return;
        }

        // 1. Extract each SQL block (ignoring comments)
        const sqlBlocks = extractDOBlocks(sqlContent);
        if (sqlBlocks.length === 0) {
            console.log('ℹ️  No valid SQL blocks found in the approved projects file');
            return;
        }

        // 2. Execute each block sequentially

        console.log('🚀 Executing approved projects...');
        console.log('SQLBlock : ', sqlBlocks);
        for (const block of sqlBlocks) {
            try {
                // Add the final semicolon if missing
                const fullQuery = block.endsWith(';') ? block : `${block};`;
                console.log('SQL Block to execute :', fullQuery);
                await db.execute(sql.raw(fullQuery));
                console.log(`✅ Successfully executed block:\n${block.substring(0, 100)}...`);
            } catch (err) {
                console.error(`❌ Error executing block:`, err);
                throw err; // Stop if an error occurs
            }
        }

        console.log('✅ All approved projects have been added to the database!');

        // Clear the SQL file after successful execution
        writeFileSync(sqlFilePath, '-- Approved projects will be added here\n-- This file is auto-generated by the approval system\n\n');
        console.log('🧹 Cleared the approved projects file');

    } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
            console.log('ℹ️  No approved projects file found. Creating one...');
            writeFileSync(sqlFilePath, '-- Approved projects will be added here\n-- This file is auto-generated by the approval system\n\n');
        } else {
            console.error('❌ Error:', error);
            throw error;
        }
    }
}

approveProjects().catch(console.error);
