import db from "./index";
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { sql } from "drizzle-orm";

/**
 * Execute approved projects from the SQL file
 * This script reads 005_approved_projects.sql and executes it
 * Then clears the file after successful execution
 */
async function approveProjects() {
    const sqlFilePath = join(__dirname, 'migrations', '005_approved_projects.sql');
    
    try {
        console.log('📂 Reading approved projects SQL file...');
        const sqlContent = readFileSync(sqlFilePath, "utf-8");
        
        if (!sqlContent.trim()) {
            console.log('ℹ️  No approved projects to process');
            return;
        }

        console.log('🚀 Executing approved projects...');
        await db.execute(sql.raw(sqlContent));
        
        console.log('✅ All approved projects have been added to the database!');
        
        // Clear the SQL file after successful execution
        writeFileSync(sqlFilePath, '-- Approved projects will be added here\n-- This file is auto-generated by the approval system\n\n');
        console.log('🧹 Cleared the approved projects file');
        
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
            console.log('ℹ️  No approved projects file found. Creating one...');
            writeFileSync(sqlFilePath, '-- Approved projects will be added here\n-- This file is auto-generated by the approval system\n\n');
        } else {
            console.error('❌ Error:', error);
            throw error;
        }
    }
}

approveProjects().catch(console.error);
